import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-white border-b border-gray-200 shadow-sm mb-8">
          <div className="max-w-4xl mx-auto px-4 flex h-16 items-center gap-8">
            <a href="/" className="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors">Home</a>
            <a href="/about" className="text-gray-700 hover:text-blue-600 transition-colors">About</a>
            <a href="/projects" className="text-gray-700 hover:text-blue-600 transition-colors">Projects</a>
            <a href="/contact" className="text-gray-700 hover:text-blue-600 transition-colors">Contact</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
